export enum ErrorCode {
    // custom
    NO_FILE_ADDED = "NO_FILE_ADDED",
    CANT_START_FILE_TRANSLATION = "CANT_START_FILE_TRANSLATION",
    CANT_START_RECORDING = "CANT_START_RECORDING",
    MIC_NOT_ALLOWED = "MIC_NOT_ALLOWED",
    MAX_SIZE_EXCEEDED = "MAX_SIZE_EXCEEDED",
    NO_TEXT_RECOGNIZED = "NO_TEXT_RECOGNIZED",
    E_FAILED_IN_TRANSLATION = "E_FAILED_IN_TRANSLATION",

    // http response codes that should be handeled
    "E_504" = "E_504",
}
