export enum AudioErrorCase {
    USER_CONSENT_FAILED = "USER_CONSENT_FAILED",
    RECORDER_TIMEOUT = "RECORDER_TIMEOUT",
    ALREADY_RECORDING = "ALREADY_RECORDING",
    MIC_NOT_ALLOWED = "MIC_NOT_ALLOWED",
    CANT_START_RECORDING = "CANT_START_RECORDING",
    MAX_SIZE_EXCEEDED = "MAX_SIZE_EXCEEDED"
}